# Overview

FLIM Playground transforms raw FLIM data into single-cell numerical and categorical features, ensuring smooth integration with [downstream analysis](data_analysis.qmd). All steps are seamlessly connected through interactive widgets, with built-in error checking and reporting to ensure correctness.

It is consisted of the following steps:

1. [Configuration](data_extraction_config.qmd): user can configure the system once and apply it to future data. It facilitates the channel-centric framework that balances flexibility and usability. 
2. [FOV Metadata Organization](fov_metadata.qmd): each experiment sitting consists of multiple field of views (FOVs). This steps helps user organize the metadata of the FOVs. 
3. [Calibration](calibration.qmd): it provides [IRF shift-based calibration](calibration.qmd#irf-shift-calibration) and [reference dye-based calibration](calibration.qmd#reference-dye-calibration). 
4. Single cell numerical feature extraction including, per channel:
    - [Lifetime fitting features](lifetime_fit.qmd): fit an exponential decay curve to the measured decay and extract lifetime features. It also accepts prefitted pixel-level lifetime features from [SPCImage](https://www.becker-hickl.com/products/spcimage/) and aggregates pixel-level lifetime features to cell-level lifetime features. 
    - [Phasor features](lifetime_fit_free.qmd): calculate the phasor features such as the phasor coordinates. 
    - [Morphology features](intensity_morphology.qmd): calculate morphology features based on the ROI mask. 
    - [Texture features](intensity_texture.qmd): calculate texture features based on the intensity image and the ROI mask. 
5. [Categorical feature extraction](categorical_feature_extraction.qmd): based on the FOV name, extract the categorical features such as the treatment, time point, etc. 

INSERT FIGURE HERE (FIGURE 3)