# Textural Features
FLIM Playground extracts single-cell texture features based on the intensity image and the ROI mask from each acquisition *channel*. For an example application, refer to this [paper](https://pubmed.ncbi.nlm.nih.gov/31081599/) which used CellProfiler to extract the texture features. 

The first step is to create a single cell intensity image for each cell based on the ROI mask and the intensity image. Then a list of texture features (the list may be extended in the future) is calculated:  

## Granularity
$Granularity_n$ is the percentage of intensity removed when bright objects of $n$ pixels in diameter are removed. A disk of radius $n$ is created, and a morphological opening is performed on the single-cell intensity image. The difference between the original and the opened image is the bright objects to be removed. The granularity value, ranging from 0 to 1, is calculated as the ratio of the removed intensity to the total intensity. 

$n = 1, 3, 5, 7, 9$ are calculated. 

Semantically, higher granularity at smaller scales implies higher fragmentation. 

## Radial Distribution
To calculate the radial distribution, each cell intensity image is partitioned into $4$ concentric rings, and the intensity fraction over the total intensity for each ring is calculated. For example, a higher fraction in ring 1 implies that signals are more concentrated at the center of the cell, whereas a higher fraction in ring 4 implies that signals are more concentrated at the cell edge.

## Mass Displacement
Mass displacement defines the Euclidean distance (in pixels) between the intensity-weighted centroid of the cell ROI and the geometric centroid of the same ROI.

## Intensity Sum
Intensity sum is defined as the sum of pixel intensities within the cell intensity image.

In the final dataset, feature names are prefixed by the combination of the feature extractor name (i.e. `Intensity texture`) and the channel name, allowing [Data Analysis](data_analysis.qmd) to group the features. For example, `Intensity texture_nadh: granularity_1` means the percentage of intensity removed when bright objects of 1-pixel diameter are removed in the NAD(P)H channel. 